# Generated by Django 6.0.1 on 2026-08-04 12:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='church',
            name='primary_phone',
        ),
        migrations.AddField(
            model_name='church',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the church', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number with country code', max_length=128, null=True, region=None),
        ),
    ]
