# Generated by Django 6.0.1 on 2026-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_church_primary_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.CharField(blank=True, help_text='Auto-generated church code (CH-001)', max_length=20, null=True, unique=True),
        ),
    ]
