# Generated by Django 6.0.1 on 2026-08-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_bill_note_bill_payment_method_bill_payment_receipt_and_more'),
    ]

    operations = [
    ]