# Generated by Django 6.0.1 on 2026-08-06 07:15

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_church_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type_code', models.CharField(help_text='Unique code for the tax type (e.g., GST, VAT, ST)', max_length=20, unique=True)),
                ('tax_type_name', models.CharField(help_text='Full name of the tax type (e.g., Goods and Services Tax)', max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country where this tax type is applicable', max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax type is currently active')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about this tax type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Type',
                'verbose_name_plural': 'Tax Types',
                'ordering': ['tax_type_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='churchsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Church Subscription', 'verbose_name_plural': 'Church Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='church',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='church',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='package',
            name='upgrade_rate_monthly',
        ),
        migrations.RemoveField(
            model_name='package',
            name='upgrade_rate_yearly',
        ),
        migrations.AddField(
            model_name='church',
            name='address',
            field=models.TextField(blank=True, help_text='Street address, building name, etc. (Address Line 1)', null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='churchsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique package code (e.g., PKG-001)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='church',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, etc. (Address Line 2)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number with country code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='churchsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='churchsubscription',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Number of months purchased (e.g. 3, 6, 12)'),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_code', models.CharField(help_text='Unique code for the tax rate (e.g., GST-18, VAT-12)', max_length=20, unique=True)),
                ('tax_rate_name', models.CharField(help_text='Name of the tax rate (e.g., GST @ 18%, VAT @ 12%)', max_length=100)),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Tax rate percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('effective_from', models.DateField(help_text='Date from which this tax rate is effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this tax rate is effective (leave blank for no end date)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax rate is currently active')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about this tax rate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.ForeignKey(help_text='Tax type this rate belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='registry.taxtype')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['tax_type', '-effective_from'],
                'unique_together': {('tax_type', 'rate_percentage', 'effective_from')},
            },
        ),
    ]
