# Generated by Django 6.0.1 on 2026-08-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_remove_church_address_line2_remove_church_phone_and_more'),
        ('registry', '0005_bill_note_bill_payment_method_bill_payment_receipt_and_more'),
    ]

    operations = [
    ]
