# Generated by Django 6.0.1 on 2026-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_merge_20260806_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsubscription',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Number of months purchased - ONLY affects end_date, NOT price'),
        ),
    ]
