# Generated by Django 6.0.1 on 2026-08-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchsubscription_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsubscription',
            name='locked_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Member capacity at time of purchase', null=True),
        ),
        migrations.AddField(
            model_name='churchsubscription',
            name='locked_package_name',
            field=models.CharField(blank=True, help_text='Package name at time of purchase', max_length=100),
        ),
        migrations.AddField(
            model_name='churchsubscription',
            name='locked_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per member at time of purchase', max_digits=8, null=True),
        ),
    ]
