# Generated by Django 6.0.1 on 2026-08-10 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_churchsubscription_locked_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='priest',
            name='house_name',
        ),
        migrations.AddField(
            model_name='priest',
            name='address_line1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priest',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priest',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vicars/'),
        ),
        migrations.AddField(
            model_name='priest',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priest',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priest',
            name='designation',
            field=models.CharField(choices=[('MAIN', 'Vicar'), ('ASSISTANT', 'Assistant Vicar')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='priest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
