# Generated by Django 6.0.1 on 2026-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_remove_priest_address_remove_priest_house_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='priest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='priest',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='family_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='priest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
