# Generated by Django 6.0.1 on 2026-08-11 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_remove_priest_created_at_remove_priest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
