# Generated by Django 6.0.1 on 2026-08-18 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_member_created_at_member_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathregister',
            name='status',
        ),
        migrations.AlterField(
            model_name='deathregister',
            name='died_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deathregister',
            name='funeral_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deathregister',
            name='reason_of_death',
            field=models.TextField(),
        ),
    ]
