# Generated by Django 6.0.1 on 2026-08-19 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_tombtype_created_at_tombtype_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
