# Generated by Django 6.0.1 on 2026-08-24 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_subscription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tombfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tombfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
