# Generated by Django 6.0.1 on 2026-08-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_tombfee_created_at_tombfee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
