# Generated by Django 6.0.1 on 2026-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_events_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
