# Generated by Django 6.0.1 on 2026-08-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_offering_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='updated_at',
        ),
    ]
