# Generated by Django 6.0.1 on 2026-08-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_remove_events_updated_at_remove_offering_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
