# Generated by Django 6.0.1 on 2026-07-07 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='registry.church')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='registry.events')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='registry.member')),
            ],
        ),
    ]
