# Generated by Django 6.0.1 on 2026-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_events_updated_at_offering_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregister',
            name='tomb_charge',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
