# Generated by Django 6.0.1 on 2026-07-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
