# Generated by Django 6.0.1 on 2026-08-31 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_alter_deathregister_tomb_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathregister',
            name='tomb_charge',
        ),
        migrations.RemoveField(
            model_name='deathregister',
            name='tomb_type',
        ),
        migrations.AddField(
            model_name='deathregister',
            name='tomb_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records', to='registry.tombfee'),
        ),
    ]
