# Generated by Django 6.0.1 on 2026-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_remove_deathregister_tomb_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
