# Generated by Django 6.0.1 on 2026-07-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_accountgroupmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountGroupMaster',
        ),
    ]
