# Generated by Django 6.0.1 on 2026-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_baptism_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
