# Generated by Django 6.0.1 on 2026-07-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_delete_accountgroupmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_date', models.DateField()),
                ('visitor_address', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='registry.church')),
            ],
        ),
    ]
