# Generated by Django 6.0.1 on 2026-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_marriage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='member_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
