# Generated by Django 6.0.1 on 2026-09-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_alter_package_code_alter_package_member_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsubscription',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Number of months purchased - only affects end_date'),
        ),
    ]
