# Generated by Django 6.0.1 on 2026-07-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_accountgroupmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedgerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_code', models.IntegerField(blank=True, null=True)),
                ('ledger_name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('reserved', models.BooleanField(default=False)),
                ('op_balance', models.FloatField(blank=True, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='registry.accountgroupmaster')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgers', to='registry.church')),
            ],
        ),
    ]
