# Generated by Django 6.0.1 on 2026-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_alter_churchsubscription_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='member_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
