# Generated by Django 6.0.1 on 2026-09-11 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_alter_package_member_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledgermaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountledgermaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='member_limit',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
