# Generated by Django 6.0.1 on 2026-07-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_accountledgermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.IntegerField()),
                ('ref_no', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('party_name', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('amount', models.FloatField()),
                ('narration', models.CharField(blank=True, max_length=300, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('account_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registry.accountledgermaster')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registry.church')),
            ],
        ),
    ]
