# Generated by Django 6.0.1 on 2026-07-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_paymentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_code', models.IntegerField()),
                ('committee_name', models.CharField(max_length=50)),
                ('committee_from_date', models.DateField()),
                ('committee_to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='registry.church')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='registry.church')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registry.committeemaster')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_members', to='registry.designation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='registry.member')),
            ],
        ),
        migrations.CreateModel(
            name='QurbanaReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('qurbana_date', models.DateField()),
                ('narration', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qurbana_receipts', to='registry.church')),
            ],
        ),
    ]
