# Generated by Django 6.0.1 on 2026-09-14 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_accountledgermaster_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroupmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountgroupmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
