# Generated by Django 6.0.1 on 2026-07-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0032_committeemaster_committeemember_qurbanareceipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
