# Generated by Django 6.0.1 on 2026-09-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0032_accountgroupmaster_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormaster',
            name='reason_to_visit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
