# Generated by Django 6.0.1 on 2026-07-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0033_alter_member_age'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('family', 'house_name', 'is_family_head')},
        ),
    ]
