# Generated by Django 6.0.1 on 2026-09-18 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0033_visitormaster_reason_to_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitormaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
