# Generated by Django 6.0.1 on 2026-07-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0034_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
    ]
