# Generated by Django 6.0.1 on 2026-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0034_visitormaster_created_at_visitormaster_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemaster',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='committeemaster',
            name='committee_code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='CommitteeMember',
        ),
    ]
