# Generated by Django 6.0.1 on 2026-07-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0035_alter_member_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='asst_vicar1',
        ),
        migrations.RemoveField(
            model_name='church',
            name='asst_vicar2',
        ),
        migrations.RemoveField(
            model_name='church',
            name='asst_vicar3',
        ),
        migrations.RemoveField(
            model_name='church',
            name='vicar',
        ),
    ]
