# Generated by Django 6.0.1 on 2026-10-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0036_legacybaptism_legacydeath_legacymarriage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='god_father',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='god_mother',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
