# Generated by Django 6.0.1 on 2026-07-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0036_remove_church_asst_vicar1_remove_church_asst_vicar2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('church', 'family_name')},
        ),
    ]
