# Generated by Django 6.0.1 on 2026-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_alter_family_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('church', 'email')},
        ),
    ]
