# Generated by Django 6.0.1 on 2026-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_alter_member_email_alter_member_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='house_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
