# Generated by Django 6.0.1 on 2026-07-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_member_house_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
