# Generated by Django 6.0.1 on 2026-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0040_alter_member_unique_together_alter_member_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriage',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='family',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='relation_of_bride_with_main_member',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='relation_of_groom_with_main_member',
        ),
        migrations.AddField(
            model_name='marriage',
            name='bride_family_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='marriage',
            name='bride_house_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='minister_of_marriage',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='nationality_of_bride',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='nationality_of_groom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='register_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='witness_bride_side',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='witness_groom_side',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='VilichCholluKuri',
        ),
    ]
