# Generated by Django 6.0.1 on 2026-07-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0041_alter_marriage_options_remove_marriage_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], max_length=20),
        ),
    ]
