# Generated by Django 6.0.1 on 2026-07-29 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0043_priest_date_from_priest_date_to_priest_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='priest_type',
        ),
        migrations.AddField(
            model_name='priest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priest',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priest',
            name='designation',
            field=models.CharField(choices=[('MAIN', 'Main Priest'), ('ASSISTANT', 'Assistant Priest')], default='ASSISTANT', max_length=20),
        ),
    ]
