# Generated by Django 6.0.1 on 2026-07-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0044_remove_priest_priest_type_priest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deathregister',
            options={'ordering': ['-created_at']},
        ),
    ]
